-- Apply once to existing SevaHub databases before deploying this update.
ALTER TABLE bookings
  MODIFY status ENUM('PENDING','BARGAINING','COUNTER_OFFER_PENDING_USER','ACCEPTED','REJECTED','IN_PROGRESS','COMPLETED','CANCELLED') DEFAULT 'PENDING',
  MODIFY completion_pin VARCHAR(255),
  ADD COLUMN IF NOT EXISTS tpin_attempts INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS customer_tpin VARCHAR(6),
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP NULL;
ALTER TABLE bargain_offers ADD COLUMN IF NOT EXISTS responded_at TIMESTAMP NULL;
